name: MTA Operator E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  MTA_OPERATOR_REPOSITORY: https://github.com/windup/windup-operator.git
  MTA_OPERATOR_REVISION: master
  MTA_OPERATOR_DIR: MTA_OPERATOR

jobs:
   minikube:
    name: K8S
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.12.0,v1.19.2]
        suite: ['quarkus','quarkus-native','springboot','webapp','other', 'dockerfile']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.0.1
        with:
          minikube version: v1.13.1
          kubernetes version: ${{ matrix.kubernetes }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: --force

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build operator image
        run: cd $JKUBE_DIR && /
             mvn clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true -DskipTests

      - name: Deploy operator
        run: cd $JKUBE_DIR && /
             cd src/main/resources/k8s/def && /
             ./script.create.all.sh &&
             kubectl apply -f ../../../../test/resources/windup-test.yaml

      - name: Get k8s objects
        id: getobjects
        run: kubectl get pods -n windup -o name | wc -l

      - name: Assert operator
        uses: therussiankid92/gat
        with:
          assertion: should.equal
          expected: 3
          actual: ${{steps.getobjects.outputs}}
