apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: windup-operator
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - deployments
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - list
    - watch
- apiGroups:
    - windup.jboss.org
  resources:
    - windups
  verbs:
    - list
    - watch