apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: windup-operator-role-binding
  namespace: rhamt
  labels:
      application: windup
subjects:
  - kind: ServiceAccount
    name: windup-operator
    namespace: rhamt
roleRef:
  kind: Role
  name: windup-operator-role
  apiGroup: rbac.authorization.k8s.io