name: MTA Operator E2E Tests

on: [push,pull_request]

jobs:
   minikube:
    name: K8S
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.0.1
        with:
          minikube version: v1.13.1
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: --force

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build operator image
        run: cd ${{github.workspace}} &&
             docker login -u ${{secrets.DOCKERIO_LOGIN}} -p ${{secrets.DOCKERIO_PASS}} &&
             mvn clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true -DskipTests

      - name: Deploy operator
        run: cd ${{github.workspace}} &&
             cd src/main/resources/k8s/def &&
             ./script.create.all.sh &&
             kubectl apply -f ../../../../test/resources/windup-test.yaml

      - name: Get k8s objects
        id: getobjects
        run: echo "::set-output name=value::$(kubectl get pods -n windup -o name | wc -l)"
        shell: bash

      - name: Operator Test
        uses: therussiankid92/gat@v1.3
        with:
          assertion: should.equal
          expected: 3
          actual: ${{jobs.minikube.steps.getobjects.outputs.value}}
